<?php

// Database Connection
include('../config.php');

//include ang autoload gikan sa composer
require_once 'vendor/autoload.php';

use Endroid\QrCode\QrCode;
use Endroid\QrCode\Writer\PngWriter;

define('ENCRYPTION_KEY', 'JoyGwapa123'); //encryption key
define('ENCRYPTION_METHOD', 'AES-256-CBC');

// Encrypt the content for the QR code
function encryptContent($content)
{
    $key = hash('sha256', ENCRYPTION_KEY);
    $iv = substr(hash('sha256', 'unique_initialization_vector'), 0, 16);
    return openssl_encrypt($content, ENCRYPTION_METHOD, $key, 0, $iv) . ':' . base64_encode($iv);
}

// Function to fetch the province name by its code
function getProvinceName($provinceCode)
{
    $url = "https://psgc.gitlab.io/api/provinces/{$provinceCode}/";
    $response = file_get_contents($url);
    $data = json_decode($response, true);
    return $data['name'] ?? null; // Return the name or null if not found
}

// Function to fetch the city name by its code
function getCityName($cityCode)
{
    $url = "https://psgc.gitlab.io/api/cities-municipalities/{$cityCode}/";
    $response = file_get_contents($url);
    $data = json_decode($response, true);
    return $data['name'] ?? null; // Return the name or null if not found
}

// Function to fetch the city name by its code
function getBarangayName($barangayCode)
{
    $url = "https://psgc.gitlab.io/api/barangays/{$barangayCode}/";
    $response = file_get_contents($url);
    $data = json_decode($response, true);
    return $data['name'] ?? null; // Return the name or null if not found
}

// Check if the form is submitted
if ($_SERVER['REQUEST_METHOD'] == 'POST') {
    // User inputs
    $lastname = strtoupper($_POST['lastname']);
    $firstname = strtoupper($_POST['firstname']);
    $middle_initial = isset($_POST['middle_initial']) ? trim($_POST['middle_initial']) : '';
    if (strcasecmp($middle_initial, "N/A") === 0) {
        $middle_initial = '';
    }
    $middle_initial = strtoupper($middle_initial);
    $suffix = strtoupper($_POST['suffix']);
    $age = $_POST['age'];
    $gender = strtoupper($_POST['gender']);
    $contact_number = $_POST['contact_number'];
    $provinceCode = !empty($_POST['province']) ? strtoupper(trim($_POST['province'])) : null;
    $cityCode = !empty($_POST['city']) ? strtoupper(trim($_POST['city'])) : null;
    $barangayCode = !empty($_POST['barangay']) ? strtoupper(trim($_POST['barangay'])) : null;
    $district = !empty($_POST['district']) ? 'DISTRICT ' . strtoupper($_POST['district']) : null;
    $purok = !empty($_POST['purok']) ? strtoupper($_POST['purok']) : null;


    // Fetch the province and city names based on the codes
    $provinceName = $provinceCode ? strtoupper(getProvinceName($provinceCode)) : null;
    $cityName = $cityCode ? strtoupper(getCityName($cityCode)) : null;
    $barangayName = $barangayCode ? strtoupper(getBarangayName($barangayCode)) : null;

    // Concatenate inputs for full name and address
    $full_name = "$lastname, $firstname $middle_initial $suffix";
    $address = "$purok, $district, $barangayName, $cityName, $provinceName";

    // Insert data into the database to get the unique ID
    $stmt = $conn->prepare("INSERT INTO residents (full_name, age, gender, contact_number, address) VALUES (?, ?, ?, ?, ?)");
    $stmt->bind_param("sisss", $full_name, $age, $gender, $contact_number, $address);
    $stmt->execute();

    // Get the unique ID generated by the database
    $user_id = $stmt->insert_id;  // This gives the unique ID of the newly inserted record

    // Concatenate the unique ID to the QR content
    $qr_content = "$user_id, $full_name, $age, $gender, $contact_number, $address";
    $encrypted_content = encryptContent($qr_content);

    // Generate and save QR
    $qr = new QrCode($encrypted_content);
    $writer = new PngWriter();
    $file_name = '../../qrcodes/' . uniqid() . '.png';
    $writer->write($qr)->saveToFile($file_name);

    // Update the database with the QR code filename
    $stmt_update = $conn->prepare("UPDATE residents SET qr_code = ? WHERE id = ?");
    $stmt_update->bind_param("si", $file_name, $user_id);
    $stmt_update->execute();
    $stmt_update->close();

    // Pass the data to the front end
    $qr_id_file = $file_name;
    $qr_details = [
        'fullname' => $full_name,
        'age' => $age,
        'gender' => $gender,
        'contact_number' => $contact_number,
        'address' => $address,
        'qr_code' => $qr_id_file,
        'user_id' => $user_id // Include the unique ID as part of the data
    ];

    // Close the original statement and connection
    $stmt->close();
    $conn->close();
}
?>

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Register User</title>
    <link rel="stylesheet" href="../css/user-register.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/html2canvas/1.4.1/html2canvas.min.js"></script>
    <script src="../JS/user-register.js" defer></script>
    <script src="../JS/user-scanner.js" defer></script>

</head>
<?php
$middle_initial = isset($_POST['middle_initial']) ? trim($_POST['middle_initial']) : '';
if (strcasecmp($middle_initial, "N/A") === 0) {
    $middle_initial = '';
}
?>

<body data-modal-status="<?php echo isset($qr_details) ? 'show' : 'hide'; ?>">
    <!-- Logo -->
    <div class="logo-container">
        <div class="logo">
            <button class="logo-button" onclick="redirectToHome()">
                <img class="logo-size" src="../PIC/logo.png" alt="Logo" />
            </button>
        </div>
        <div class="title-text">
            <h2>ETRANSACTMO REGISTER USER</h2>
        </div>
    </div>

    <div class="register-form-container">
        <!-- <button onclick="redirectToLogin()" class="btn back-btn">
            <span class="text"><i class="fas fa-arrow-left"></i>Go back to Login</span>
        </button> -->
        <form class="register-form" action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post">
            <p>Please fill-in the necessary information to generate your QR Code</p>

            <div class="input-fields">
                <!-- Last Name Field -->
                <div class="input-group">
                    <label class="custom-field">
                        <input type="text" name="lastname" placeholder="&nbsp;" required autocomplete="off" />
                        <span class="placeholder">Enter Lastname</span>
                    </label>
                </div>
                <!-- First Name Field -->
                <div class="input-group">
                    <label class="custom-field">
                        <input type="text" name="firstname" placeholder="&nbsp;" required autocomplete="off" />
                        <span class="placeholder">Enter Firstname</span>
                    </label>
                </div>
                <!-- Middle Initial Field -->
                <div class="input-group">
                    <label class="custom-field">
                        <input type="text" name="middle_initial" placeholder="&nbsp;" autocomplete="off" value="N/A" />
                        <span class="placeholder">Enter Middle Initial</span>
                    </label>
                </div>
                <!-- Suffix Field -->
                <div class="input-group">
                    <label class="custom-field">
                        <select name="suffix">
                            <option value="" selected>N/A</option>
                            <option value="Jr.">Jr.</option>
                            <option value="Sr.">Sr.</option>
                            <option value="II">II</option>
                            <option value="III">III</option>
                            <option value="IV">IV</option>
                        </select>
                        <span class="placeholder">Suffix</span>
                    </label>
                </div>
            </div>

            <div class="input-fields">
                <!-- Age Field -->
                <div class="input-group">
                    <label class="custom-field">
                        <input type="number" name="age" placeholder="&nbsp;" min="1" max="120" autocomplete="off" required />
                        <span class="placeholder">Enter Age</span>
                    </label>
                </div>

                <!-- Gender Field (Radio buttons instead of checkboxes) -->
                <h4>Gender: </h4>
                <label>
                    <input type="radio" name="gender" value="MALE" required>
                    Male
                </label>
                <label>
                    <input type="radio" name="gender" value="FEMALE" required>
                    Female
                </label>
                <label>
                    <input type="radio" name="gender" value="PREFER NOT TO SAY" required>
                    Prefer not to say
                </label>

                <!-- Contact Number Field -->
                <div class="input-group">
                    <label class="custom-field">
                        <input type="text" name="contact_number" id="contact_number"
                            required autocomplete="off"
                            value="+63"
                            maxlength="13"
                            oninput="validateContactNumber()"
                            onfocus="this.setSelectionRange(3, 3)" />
                        <span class="placeholder">Enter Contact Number</span>
                    </label>
                </div>
            </div>

            <div class="input-fields">
                <!-- Address Field -->
                <div class="input-group region-select">
                    <label class="custom-field">
                        <select id="region" name="region" onchange="loadProvinces(this.value)" required>
                            <option value="">&nbsp;</option>
                        </select>
                        <span class="placeholder">Region</span>
                    </label>
                </div>
                <div class="input-group">
                    <label class="custom-field">
                        <select id="province" name="province" onchange="loadCities(this.value)" required>
                            <option value="">&nbsp;</option>
                        </select>
                        <span class="placeholder-fixed">Province</span>
                    </label>
                </div>
                <div class="input-group">
                    <label class="custom-field">
                        <select id="city" name="city" onchange="loadBarangays(this.value)" required>
                            <option value="">&nbsp;</option>
                        </select>
                        <span class="placeholder-fixed">City/Municipality</span>
                    </label>
                </div>
                <div class="input-group">
                    <label class="custom-field">
                        <select id="barangay" name="barangay" required>
                            <option value="">&nbsp;</option>
                        </select>
                        <span class="placeholder-fixed">Barangay</span>
                    </label>
                </div>
                <div class="input-group">
                    <label class="custom-field">
                        <select id="district" name="district" required onchange="updatePurokOptions()">
                            <option value="">&nbsp;</option>
                            <option value="1">District 1</option>
                            <option value="2">District 2</option>
                            <option value="3">District 3</option>
                            <option value="4">District 4</option>
                            <option value="5">District 5</option>
                            <option value="6">District 6</option>
                            <option value="7">District 7</option>
                        </select>
                        <span class="placeholder-fixed">District</span>
                    </label>
                </div>
                <div class="input-group">
                    <label class="custom-field">
                        <select id="purok" name="purok" required>
                            <option value="">&nbsp;</option>
                        </select>
                        <span class="placeholder-fixed">Purok</span>
                    </label>
                </div>
            </div>
            <!-- Submit Button -->
            <button type="submit" class="btn login-btn" onclick="return validateForm()">
                <span class="text">Generate QR Code</span>
            </button>
        </form>
    </div>

    <!-- Modal to display the QR code and details -->
    <div id="qrModal" class="modal">

        <div class="modal-container">
            <div class="modal-title">
                <img src="../PIC/logo.png" alt="logo">
                <h4>ETRANSACTMO QR ID</h4>
            </div>
            <div class="modal-content">
                <div class="details">
                    <p><strong>Full Name:</strong> <?php echo $qr_details['fullname']; ?></p>
                    <p><strong>Age:</strong> <?php echo $qr_details['age']; ?></p>
                    <p><strong>Gender:</strong> <?php echo $qr_details['gender']; ?></p>
                    <p><strong>Contact Number:</strong> <?php echo $qr_details['contact_number']; ?></p>
                    <p><strong>Address:</strong> <?php echo $qr_details['address']; ?></p>
                </div>
                <div class="qr-code">
                    <img id="qrImage" src="<?php echo $qr_details['qr_code']; ?>" alt="QR Code">
                </div>
            </div>

        </div>
        <div class="modal-buttons">
            <button onclick="window.print()" class="btn">Print QR ID</button>
            <button onclick="downloadQR()" class="btn">Download QR ID</button>
        </div>
    </div>
    <div id="loadingMessage">
        <img id="loadingLogo" src="../Images/logo.png" alt="Loading">
    </div>
</body>

</html>